### ISSUE TITLE
snap

### ISSUE THREAD

**Issue by marado** [htop-dev/htop-dev.github.io#13]
https://htop.dev/downloads.html#binaries doesn't refer to a snap package, but one exists*. Is it official? I don't know. Other's won't either. So...

Can we place have something on that section referring to the existence of the snap package, either to point to it as official or to point out that it is not official? Thank you.

* https://snapcraft.io/htop

**Comment by BenBE** [comment]
That snap is unofficial and entirely unsupported by the htop dev team.

And while the build files for that snap [are available](https://github.com/maxiberta/htop-snap), **you are running that snap at your own risk**.

Also note, that running htop from inside snap (or docker as some people do) doesn't even provide any benefits; even more so, if your distribution already provides a packaged version of htop.

There are many ways to publish applications in lightweight container formats. We don't think any of these are useful for a native C application like htop so we do not want to endorse snap or any of its competitors.

**Comment by marado** [comment]
Thank you for the clarification... I was hoping that it could be done in some form in the website itself :-(
