### ISSUE TITLE
Getting 404 for htop_talk.pdf link

### ISSUE THREAD

**Issue by bityob** [htop-dev/htop-dev.github.io#14]
Link: https://htop.dev/htop_talk.pdf

<img src="https://github.com/htop-dev/htop/assets/20026896/44e0032c-066e-430c-bf09-190a71ea162a" width="400">

**Comment by BenBE** [comment]
Looks like this might be the talk:
https://archive.fosdem.org/2016/schedule/event/htop/attachments/slides/1167/export/events/attachments/htop/slides/1167/htop_talk.pdf

@hishamhm Is this the one to place on the homepage or are there other documents also called `htop_talk.pdf` that would fit there?

@bityob : Which page exactly was this dead link on? TIA.

**Comment by fasterit** [comment]
The footer has:
Since version 2.0, htop is now [cross-platform!](https://fosdem.org/2016/schedule/event/htop/) Check out the [video](https://youtu.be/g5GamptmWeA) and [slides](https://htop.dev/htop_talk.pdf) of Hisham's presentation at FOSDEM 2016 about how this came to be.

**Comment by bityob** [comment]
@BenBE 

https://github.com/htop-dev/htop-dev.github.io/blob/29df75ea77f2594f28217f508912e4589ee23caa/index.haml#L41

**Comment by bityob** [comment]
@BenBE 

https://github.com/htop-dev/htop-dev.github.io/blob/29df75ea77f2594f28217f508912e4589ee23caa/index.haml#L41

**Comment by hishamhm** [comment]
> Looks like this might be the talk:
https://archive.fosdem.org/2016/schedule/event/htop/attachments/slides/1167/export/events/attachments/htop/slides/1167/htop_talk.pdf

@BenBE Yes, that's the one!

**Comment by BenBE** [comment]
Should be fixed.

And man, I am absolutely happy about every single day that I don't need to touch any Ruby stuff …
