### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by akrifari** [htop-dev/htop-dev.github.io#5]
**Steps to reproduce**

1. Go to https://htop.dev/downloads.html#binaries
2. Scroll down to Gentoo bullet
3. Click `sys-process/htop`

**Current behaviour**

404

**Expected behaviour**

I'm not sure where it should point to, maybe https://packages.gentoo.org/packages/sys-process/htop?

**Comment by BenBE** [comment]
Better link may be:
https://packages.gentoo.org/packages/sys-process/htop

The old site seems to be out of order.
