### ISSUE TITLE
Add Arch Linux

### ISSUE THREAD

**Issue by ghost** [htop-dev/htop-dev.github.io#7]
htop already exists in [Arch Linux Packages](https://archlinux.org/packages/extra/x86_64/htop/), but this is not mentioned in the htop's [download's section](https://htop.dev/downloads.html)

I think it is worth explicitly mentioning it

**Comment by fasterit** [comment]
@KILR007 https://github.com/htop-dev/htop-dev.github.io is the repo for our website. PRs welcome!
